version: '3.5'
services:

  db:
    image: postgres
    volumes:
      - ./tmp/docker/db/data:/var/lib/postgresql/data

  backend:
    build: ./backend
    entrypoint: bin/docker-entrypoints/backend.sh
    command: bin/rails s -b 0.0.0.0 -p ${PORT:-3009}
    volumes:
      - ./backend:/app
      # - node_modules:/app/node_modules
      - bundle:/usr/local/bundle/
    ports:
      - "${PORT:-3009}:${PORT:-3009}"
    environment:
      DATABASE_URL: postgresql://postgres@db/app_development
      RAILS_ENV: development
      # WEBPACKER_DEV_SERVER_HOST: webpack
      # MAILER_URL: "smtp://mail?from=no-reply@heimverwaltung.localhost"
      BUNDLE_PATH: /usr/local/bundle
    depends_on:
      - db

  frontend:
    build: ./frontend
    entrypoint: bin/docker-entrypoints/frontend.sh
    command: ionic serve
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "${PORT:-8100}:${PORT:-8100}"
    # environment:
      # DATABASE_URL: postgresql://postgres@db/app_development
      # RAILS_ENV: development
      # WEBPACKER_DEV_SERVER_HOST: webpack
      # MAILER_URL: "smtp://mail?from=no-reply@heimverwaltung.localhost"
      # BUNDLE_PATH: /usr/local/bundle
    depends_on:
      - db

volumes:
  bundle:
  node_modules:
