version: '3.5'
services:

  db:
    image: postgres:alpine
    volumes:
      - ./tmp/docker/db/data:/var/lib/postgresql/data

  backend:
    build: ./backend
    entrypoint: bin/docker-entrypoints/backend.sh
    command: bin/rails s -p ${PORT:-3000} -b '0.0.0.0'
    volumes:
      - ./backend:/app
      # - node_modules:/app/node_modules
      - bundle:/usr/local/bundle/
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      DATABASE_URL: postgresql://postgres@db/app_development
      RAILS_ENV: development
      # WEBPACKER_DEV_SERVER_HOST: webpack
      # MAILER_URL: "smtp://mail?from=no-reply@heimverwaltung.localhost"
      BUNDLE_PATH: /usr/local/bundle
    depends_on:
      - db
    volumes:
      # - node_modules:/app/node_modules
      - bundle:/usr/local/bundle/

volumes:
  bundle:
  node_modules:
