version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  backend:
    build: backend/.
    command: bin/run
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres@db/
    depends_on:
      - db
